apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/ischooldevteam/ischool-profiles:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/ischooldevteam/ischool-profiles:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: ischool-profiles
        chartPath: charts/ischool-profiles
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/ischooldevteam/ischool-profiles"
          image.tag: "{{.TAG}}"
