# Generated by Django 2.0 on 2018-09-27 19:20

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ischool_profiles_core.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Display Name')),
                ('academic_rank', models.PositiveSmallIntegerField(default=0, verbose_name='Academic Weight')),
                ('associated_ad_group', models.CharField(blank=True, max_length=200, null=True, verbose_name='AD Group')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('display_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Display name')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Biography')),
                ('profile_type', models.CharField(blank=True, choices=[('faculty', 'Faculty'), ('faculty_emeriti', 'Faculty Emeriti'), ('faculty_ajunct', 'Adjunct Faculty'), ('faculty_affiliated', 'Affiliated Faculty'), ('staff', 'Staff'), ('research_staff', 'Research Staff'), ('doctoral_students', 'Doctoral Students'), ('alumni', 'Alumni'), ('student', 'Student'), ('other', 'Other')], default='other', max_length=200, verbose_name='Profile Type')),
                ('profile_image', models.ImageField(blank=True, default=None, max_length=200, null=True, upload_to=ischool_profiles_core.models.image_profile_path, verbose_name='Profile Image')),
                ('media_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('na', 'Prefer not to answer')], default='na', max_length=30, verbose_name='Gender')),
                ('suid', models.CharField(blank=True, max_length=15, null=True, verbose_name='SUID')),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('is_private', models.BooleanField(default=True, verbose_name='Privacy Status')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('creator_id', models.CharField(max_length=200, verbose_name='Creator Id')),
                ('owner_id', models.CharField(max_length=200, unique=True, verbose_name='Owner Id')),
                ('affiliations', models.ManyToManyField(related_name='profiles', to='ischool_profiles_core.Affiliation')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=200, verbose_name='Street address')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('zip_code', models.CharField(max_length=11, verbose_name='Zip Code')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='ischool_profiles_core.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Attribute Title')),
                ('value', models.CharField(blank=True, max_length=200, null=True, verbose_name='Attribute Value')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='ischool_profiles_core.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank=True, max_length=200, null=True, verbose_name='University')),
                ('gpa', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='GPA')),
                ('degree', models.CharField(blank=True, max_length=200, null=True, verbose_name='Degree')),
                ('major', models.CharField(max_length=200, verbose_name='Major')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='Graduation Date')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='ischool_profiles_core.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL Name')),
                ('url_link', models.URLField(blank=True, null=True, verbose_name='URL Link')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='ischool_profiles_core.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number format: '+999999999'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('phone_type', models.CharField(max_length=100, verbose_name='Phone Type')),
                ('best_contact_time', models.CharField(blank=True, max_length=200, null=True, verbose_name='Best time to contact')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Number')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='ischool_profiles_core.Profile')),
            ],
        ),
    ]
