"""
Django settings for ischool_profiles project. This project is based on the 
iSchool at Syracuse University's base starter project

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Ischool API Auth
ISCHOOL_API_HOST = "https://api.ischool.syr.edu/api/"
ISCHOOL_API_USER = "apiuser"
ISCHOOL_API_PASSWORD = "testing123"

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP_ENV = os.environ.get("APP_ENV", "testing")
APP_ENV_LOCAL=os.environ.get("APP_ENV_LOCAL", "true")
APP_HOST=os.environ.get("APP_HOST", "localhost")
DATABASE_DB=os.environ.get("DATABASE_DB", "testdb")
DATABASE_HOST=os.environ.get("DATABASE_HOST", "testpostgresdb")
DATABASE_USER=os.environ.get("DATABASE_USER", "ischooldevdbuser")
DATABASE_PASSWORD=os.environ.get("DATABASE_PASSWORD", "ischooldev")
DATABASE_ENGINE=os.environ.get("DATABASE_ENGINE", "django.db.backends.postgresql_psycopg2")
DATABASE_PORT=os.environ.get("DATABASE_PORT", "5432")
RABBIT_HOST = os.environ.get("RABBIT_HOST", "")
RABBIT_USER  = os.environ.get("RABBIT_USER", "")
RABBIT_PASSWORD = os.environ.get("RABBIT_PASSWORD", "")
CACHE_SERVER = os.environ.get("CACHE_SERVER", "")

IDENTITY_SERVER_URL = os.environ.get("IDENTITY_SERVER_URL", "https://sso4.ischool.syr.edu/")
IDENTITY_SERVER_CLIENT_ID = os.environ.get("IDENTITY_SERVER_CLIENT_ID", "profiles.ischool.service")
IDENTITY_SERVER_CLIENT_SECRET = os.environ.get("IDENTITY_SERVER_CLIENT_SECRET", "20080e34-fdab-464b-b72a-ccd4d5ff974a")

IDENTITY_SERVER_API_ID = os.environ.get("IDENTITY_SERVER_CLIENT_SECRET", "media.ischool.syr.edu")
IDENTITY_SERVER_API_SECRET = os.environ.get("IDENTITY_SERVER_CLIENT_SECRET", "secret")
IDENTITY_SERVER_API_SCOPE = os.environ.get("IDENTITY_SERVER_API_SCOPE", "media.ischool.syr.edu.public_service_upload")


MEDIA_SERVICE_BIN_CREATE_URL = os.environ.get("MEDIA_SERVICE_BIN_CREATE_URL", "https://staging.ischool-media.dev.ischool.syr.edu/api/v1/ischool-media/service/bin")

NATS_BASE_SERVICE_SUBJECT = "ischool.profiles"
NATS_SERVERS = []

if APP_ENV == "testing":
    NATS_SERVERS = [
        "nats://testnats:4222"
    ]
if APP_ENV == "staging" or APP_ENV == "development":
    NATS_SERVERS = [
        "nats://dev-nats-cluster.nats-io.svc.cluster.local:4222"
    ]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
if APP_ENV == "testing":
    EMAIL_BACKEND = 'django.core.mail.backends.dummy.EmailBackend'
EMAIL_HOST = 'smtp-relay.sendinblue.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'ischooltsb@syr.edu'
EMAIL_HOST_PASSWORD = 'G60VEm3gLC4MhT8a'
EMAIL_USE_TLS = True

PROXY_SERVERS = {}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u!)nj@8=&0rj_)@r!zzoqp@yaqbq0x@u2%&#qiklg-y#kwh&##'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
if APP_ENV == "development" or APP_ENV == "testing":
    DEBUG = True

USE_X_FORWARDED_HOST = True
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = True


ALLOWED_HOSTS = ['*']

ADMINS = (
    ('Nick', 'ndlyga@syr.edu'),
    ('Mike', 'mmclarke@syr.edu'),
)


# Application definition


INSTALLED_APPS = [
    'django.contrib.postgres',
    'django.contrib.staticfiles',
    'storages',
    'ischool_storage',
    'rest_framework',
    'corsheaders',
    'drf_yasg',
    'ischool_profiles_core.apps.IschoolProfilesCoreConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ischool_profiles_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': True if APP_ENV == "testing" else False,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                #'django.contrib.auth.context_processors.auth',
                "django.template.context_processors.tz",
            ],
        },
    },
]

WSGI_APPLICATION = 'ischool_profiles_api.wsgi.application'

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        "ischool_auth": {
            "type": "oauth2",
            "authorizationUrl": "https://sso4.ischool.syr.edu/connect/authorize",
            "flow": "implicit",
            "scopes": {
                "write:profile": "modifiy your profile",
                "read:profile": "read public profiles",
            }
        }
    },
}


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': DATABASE_ENGINE,
        'NAME': DATABASE_DB,
        'HOST': DATABASE_HOST,
        'USER': DATABASE_USER,
        'PASSWORD': DATABASE_PASSWORD,
        'PORT': DATABASE_PORT
    }
}


REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    #'DEFAULT_PARSER_CLASSES': (
    #    'rest_framework.parsers.JSONParser',
    #),
    'UNAUTHENTICATED_USER': 'auth_core.auth_backends.user_models.AnonymousUser',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'auth_core.auth_backends.api_identity_auth.AccessTokenIdentityServerAuth',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
}

# https://github.com/ottoyiu/django-cors-headers/
if APP_ENV == "testing":
    CORS_ORIGIN_ALLOW_ALL = True
    REST_FRAMEWORK['DEFAULT_AUTHENTICATION_CLASSES'] = ('auth_core.auth_backends.dev_auth_backend.DevelopAPIAuthentication', )
elif APP_ENV == "development":
    CORS_ORIGIN_REGEX_WHITELIST = (
        r'^(https?:\/\/)?(\-?\w+\.?)*.dev\.ischool\.syr\.edu$',
        r'^(https?:\/\/)?(\-?\w+\.?)*localhost:4200$',
        r'^http://localhost:4200',
    )
else:
    CORS_ORIGIN_REGEX_WHITELIST = (
        r'^(https?:\/\/)?(\-?\w+\.?)*ischool\.syr\.edu$',
    )


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID", "a2PYqPqhQJWSKnmuTL6l")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY", "6cHc!376JYn#[:P!")
AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME", "test.ischool.syr.edu")
AWS_S3_ENDPOINT_URL = os.environ.get("AWS_S3_ENDPOINT_URL", "https://storage2.ischool.syr.edu")


if APP_ENV == "testing":
    STATIC_URL = '/static/'
    STATIC_ROOT = os.environ.get("STATIC_ROOT", '/ischool_profiles/')
else:
    STATIC_ROOT = os.environ.get("STATIC_ROOT", '/ischool_profiles/')
    STATIC_URL = os.environ.get("STATIC_URL", AWS_S3_ENDPOINT_URL + '/' + AWS_STORAGE_BUCKET_NAME + STATIC_ROOT)
    STATICFILES_STORAGE = 'ischool_storage.storage.StaticS3Boto3Storage'


MEDIA_ROOT = STATIC_ROOT + "/"
MEDIA_URL = "/".join((STATIC_URL.rstrip("/"), "media", ""))



# Django Storages
DEFAULT_FILE_STORAGE = 'ischool_storage.storage.MediaS3Storage'


AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_QUERYSTRING_AUTH = False
AWS_IS_GZIPPED = True

GZIP_CONTENT_TYPES = (
    'text/css',
    'application/javascript',
    'application/x-javascript',
    'text/javascript'
)

